databases-pos-vs/databases-pos-vs/Models/UserViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;


namespace databseApp.Models
{
    public class UserViewModel
    {
        [Key]
        public int UserID { get; set; }
        public string Password { get; set; }
        public string FirstName_ { get; set; }
        public string LastName_ { get; set; }
        public string Email { get; set; }
        public string Role { get; set; }
        public string Address { get; set; }
        public string Zipcode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Date { get; set; }

        public string Payment_Method{ get; set; }
        public string  Shipping_Address { get; set; }
    }
}

databases-pos-vs/databases-pos-vs/Controllers/CustomerController.cs
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using databseApp.Models;
using Microsoft.Extensions.Configuration;
using Microsoft.Data.SqlClient;
using MySql.Data.MySqlClient;

namespace databseApp.Controllers
{
    public class CustomerController : Controller
    {
        
        private readonly IConfiguration _configuration;

        public CustomerController(IConfiguration configuration)
        {
            this._configuration = configuration;
        }





        public IActionResult Data()
        {
            MySqlDataAdapter daTransactions;
            DataTable dtbl = new DataTable();
            int userid = Int32.Parse(Request.Cookies["id"]);
            using (MySqlConnection sqlConnection = new MySqlConnection(_configuration.GetConnectionString("DevConnection")))
            {
                sqlConnection.Open();
                string query = "SELECT * From Transaction_Info WHERE customer_id = '"+userid+"'";
                daTransactions = new MySqlDataAdapter(query, sqlConnection);
                MySqlCommandBuilder cb = new MySqlCommandBuilder(daTransactions);
                daTransactions.Fill(dtbl);
            }
            return View(dtbl);
        }


        public async Task<IActionResult> Purchase_Details(int id)
        {
            MySqlDataAdapter daTransactions;
            DataTable dtbl = new DataTable();
            using (MySqlConnection sqlConnection = new MySqlConnection(_configuration.GetConnectionString("DevConnection")))
            {

                sqlConnection.Open();
                string query = "SELECT transaction_info_id, Products.product_id, name, size, price, quantity FROM Transaction_Info, Transactions, Products WHERE Transaction_Info.transaction_id = '"+id+"' AND transaction_info_id = '"+id+"' AND Transactions.product_id = Products.product_id";
                daTransactions = new MySqlDataAdapter(query, sqlConnection);
                MySqlCommandBuilder cb = new MySqlCommandBuilder(daTransactions);
                daTransactions.Fill(dtbl);
            }

            if (dtbl != null)
                return View(dtbl);
            else
                return RedirectToAction("Index", new { Controller = "Home", Action = "Index" });
        }
    }
}

databases-pos-vs/databases-pos-vs/Controllers/UserController.cs
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using databseApp.Models;
using Microsoft.Extensions.Configuration;
using Microsoft.Data.SqlClient;
using System.Data;
using MySql.Data.MySqlClient;
using System.Web;

namespace databseApp.Controllers
{
    public class UserController : Controller
    {
        private readonly IConfiguration _configuration;

        public UserController(IConfiguration configuration)
        {
            this._configuration = configuration;
        }

        public IActionResult Logout()
        {
            HttpContext.Response.Cookies.Delete("role");
            HttpContext.Response.Cookies.Delete("email");
            HttpContext.Response.Cookies.Delete("name");
            HttpContext.Response.Cookies.Delete("id");

            return RedirectToAction("Index", new { Controller = "Home", Action = "Index" });
        }

        // GET: User Login
        public IActionResult UserIndex()
        {
                UserViewModel userViewModel = new UserViewModel();
                return View(userViewModel); 
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UserIndex([Bind("FirstName_, LastName_, Email, Password, Role, UserID")] UserViewModel userViewModel)
        {
            DataTable dtbl = new DataTable();
            DataTable dtbl2 = new DataTable();
            MySqlDataAdapter daUsers;
            MySqlDataAdapter daName;

            using (MySqlConnection sqlConnection = new MySqlConnection(_configuration.GetConnectionString("DevConnection")))
            {
                sqlConnection.Open();
                string sql = "SELECT * FROM Users WHERE email = '"+userViewModel.Email+"' AND password = '"+userViewModel.Password+"'";
                daUsers = new MySqlDataAdapter(sql, sqlConnection);
                daUsers.Fill(dtbl);

                if (dtbl.Rows.Count == 1)
                {
                    userViewModel.UserID = Convert.ToInt32(dtbl.Rows[0]["user_id"].ToString());
                    userViewModel.Role = dtbl.Rows[0]["role"].ToString(); 
                    if (userViewModel.Role == "customer")
                    {
                        string temp = "SELECT FirstName FROM Customers WHERE CustomerID = '"+userViewModel.UserID+"'";
                        daName = new MySqlDataAdapter(temp, sqlConnection);
                        daName.Fill(dtbl2);
                        userViewModel.FirstName_ = dtbl2.Rows[0]["FirstName"].ToString();
                    } 
                    else
                    {
                        string temp = "SELECT FirstName FROM Employees WHERE employee_id = '"+userViewModel.UserID+"'";
                        daName = new MySqlDataAdapter(temp, sqlConnection);
                        daName.Fill(dtbl2);
                        userViewModel.FirstName_ = dtbl2.Rows[0]["FirstName"].ToString();
                    }
                    sqlConnection.Close();
                    //save account in localstorage as cookie
                    HttpContext.Response.Cookies.Append("id", (userViewModel.UserID).ToString());
                    HttpContext.Response.Cookies.Append("email", userViewModel.Email);
                    HttpContext.Response.Cookies.Append("role", userViewModel.Role);
                    HttpContext.Response.Cookies.Append("name", userViewModel.FirstName_);

                    return RedirectToAction("Index", new { Controller = "Home", Action = "Index" });
                }
                sqlConnection.Close();
            }
            return View(userViewModel);
        }


        // GET:
        public IActionResult Create()
        {
            UserViewModel userViewModel = new UserViewModel();
            return View(userViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("FirstName_, LastName_, Email, Password, Role, UserID, Address, Zipcode, City, State")] UserViewModel userViewModel)
        {
            MySqlDataAdapter daProducts;
            DataTable dtbl = new DataTable();
            if (ModelState.IsValid)
            {
                using (MySqlConnection sqlConnection = new MySqlConnection(_configuration.GetConnectionString("DevConnection")))
                {
                    sqlConnection.Open();
                    MySqlCommand sqlCmd = new MySqlCommand("CreateNewUser", sqlConnection);
                    sqlCmd.CommandType = CommandType.StoredProcedure;
                    sqlCmd.Parameters.AddWithValue("@FirstName_", userViewModel.FirstName_);
                    sqlCmd.Parameters.AddWithValue("@LastName_", userViewModel.LastName_);
                    sqlCmd.Parameters.AddWithValue("@Email", userViewModel.Email);
                    sqlCmd.Parameters.AddWithValue("@Password", userViewModel.Password);
                    sqlCmd.Parameters.AddWithValue("@Role", userViewModel.Role);
                    sqlCmd.Parameters.AddWithValue("@Address_", userViewModel.Address);
                    sqlCmd.Parameters.AddWithValue("@Zipcode_", userViewModel.Zipcode);
                    sqlCmd.Parameters.AddWithValue("@City_", userViewModel.City);
                    sqlCmd.Parameters.AddWithValue("@State_", userViewModel.State);
                    sqlCmd.ExecuteNonQuery();

                    string sql = "SELECT user_id FROM Users WHERE email = '"+userViewModel.Email+"' AND password = '"+userViewModel.Password+"'";                    
                    daProducts = new MySqlDataAdapter(sql, sqlConnection);
                    MySqlCommandBuilder cb = new MySqlCommandBuilder(daProducts);
                    daProducts.Fill(dtbl);
                    userViewModel.UserID = Convert.ToInt32(dtbl.Rows[0]["user_id"].ToString());
                }
                HttpContext.Response.Cookies.Append("id", (userViewModel.UserID).ToString());
                HttpContext.Response.Cookies.Append("email", userViewModel.Email);
                HttpContext.Response.Cookies.Append("role", userViewModel.Role);
                HttpContext.Response.Cookies.Append("firstname", userViewModel.FirstName_);

                return RedirectToAction("Index", new { Controller = "Home", Action = "Index" });   

            }
            return View(userViewModel);
        }


        // GET: /User/TransactionHistoryReport (Work on later)
        public IActionResult TransactionHistoryReport()
        {
            UserViewModel userViewModel = new UserViewModel();
            return View(userViewModel);
        }


        public async Task<IActionResult> Details()
        {
            UserViewModel userViewModel = FetchUserByID();
             return View(userViewModel);
        }

        public IActionResult Edit(int id)
        {
            UserViewModel userViewModel = FetchUserByID();
            return View(userViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([Bind("UserID, Password, FirstName_, LastName_, Email, Address, Zipcode, City, State, Date")] UserViewModel userViewModel)
        {

            //function to check if email exists in order to avoid repetition!!!!!!!
            if (ModelState.IsValid)
            {
                using (MySqlConnection sqlConnection = new MySqlConnection(_configuration.GetConnectionString("DevConnection")))
                {
                    
                    sqlConnection.Open();
                     MySqlCommand sqlCmd;

                    if (Request.Cookies["role"] == "customers")
                    {
                        sqlCmd = new MySqlCommand("EditCustomer", sqlConnection);
                        sqlCmd.CommandType = CommandType.StoredProcedure;
                        sqlCmd.Parameters.AddWithValue("@id", userViewModel.UserID);
                        sqlCmd.Parameters.AddWithValue("@FirstName_", userViewModel.FirstName_);
                        sqlCmd.Parameters.AddWithValue("@LastName_", userViewModel.LastName_);
                        sqlCmd.Parameters.AddWithValue("@Email_", userViewModel.Email);
                        sqlCmd.Parameters.AddWithValue("@Password_", userViewModel.Password);
                        sqlCmd.Parameters.AddWithValue("@Role", userViewModel.Role);
                        sqlCmd.Parameters.AddWithValue("@Address_", userViewModel.Address);
                        sqlCmd.Parameters.AddWithValue("@Zipcode_", userViewModel.Zipcode);
                        sqlCmd.Parameters.AddWithValue("@City_", userViewModel.City);
                        sqlCmd.Parameters.AddWithValue("@State_", userViewModel.State);
                                            sqlCmd.ExecuteNonQuery();
                    sqlConnection.Close();
                    }
                    else
                    {
                        sqlCmd = new MySqlCommand("EditEmployee", sqlConnection);
                        sqlCmd.CommandType = CommandType.StoredProcedure;
                        sqlCmd.Parameters.AddWithValue("@id", userViewModel.UserID);
                        sqlCmd.Parameters.AddWithValue("@FirstName_", userViewModel.FirstName_);
                        sqlCmd.Parameters.AddWithValue("@LastName_", userViewModel.LastName_);
                        sqlCmd.Parameters.AddWithValue("@Email_", userViewModel.Email);
                        sqlCmd.Parameters.AddWithValue("@Password_", userViewModel.Password);
                                            sqlCmd.ExecuteNonQuery();
                    sqlConnection.Close();
                    }

                }
                return RedirectToAction("Details");
            }
            return RedirectToAction("Details");
        }

        public UserViewModel FetchUserByID()
        {

databases-pos-vs/databases-pos-vs/Views/User/Create.cshtml
@model databseApp.Models.UserViewModel
@{
    ViewData["Title"] = "Create";
}

<section class="loginform cf">
    <form asp-action="Create">
		<ul>
			<li>
				<label asp-for="FirstName_">First Name</label>
				<input asp-for="FirstName_" type="text" name="FirstName_" placeholder="John" required>
			</li>
			<li>
				<label asp-for="LastName_">Last Name</label>
				<input asp-for="LastName_" type="text" name="LastName_" placeholder="Smith" required>
			</li>

			<li>
				<label asp-for="Email">Email</label>
				<input asp-for="Email" type="email" name="Email" placeholder="yourname@email.com" required>
			</li>
			<li>
				<label asp-for="Password">Password</label>
				<input asp-for="Password" name="Password" placeholder="Password" required>
			<li>
				<label asp-for="Address">Address</label>
				<input asp-for="Address" type="text" name="Address" required>
			</li>
			<li>
				<label asp-for="City">City</label>
				<input asp-for="City" type="text" name="City" required>
			</li>
			<li>
				<label asp-for="State">State</label>
				<input asp-for="State" type="text" name="State" required>
			</li>
			<li>
				<label asp-for="Zipcode">Zipcode</label>
				<input asp-for="Zipcode" type="text" name="Zipcode" required>
			

			<br />
			<br />
			<select asp-for="Role">
				<option value="" style="display:none">Choose an account</option>
				<option value="customer">Customer</option>
				<option value="employee">Employee</option>
			</select>
			<br />
			<input type="submit" value="Next">
		</ul>
    </form>
</section>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

databases-pos-vs/databases-pos-vs/Views/User/CreateCus.cshtml
@model databseApp.Models.UserViewModel
@{
    ViewData["Title"] = "Create Customer";
}

databases-pos-vs/databases-pos-vs/Views/User/CreateNext.cshtml
@model databseApp.Models.UserViewModel
@{
    ViewData["Title"] = "CreateCustomer";
}

<h1> helloooooooooo </h1>

<section class="loginform cf">
	<form asp-action="Create">
		<ul>
			<li>
				<label asp-for="Address">Address</label>
				<input asp-for="Address" type="text" name="Address" required>
			</li>
			<li>
				<label asp-for="City">City</label>
				<input asp-for="City" type="text" name="City" required>
			</li>
			<li>
				<label asp-for="State">State</label>
				<input asp-for="State" type="text" name="State" required>
			</li>
			<li>
				<label asp-for="Zipcode">Zipcode</label>
				<input asp-for="Zipcode" type="text" name="Zipcode" required>
			</li>

		</ul>
		<input type="submit" value="Next">
	</form>
</section>


@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

databases-pos-vs/databases-pos-vs/Views/User/Details.cshtml
@model databseApp.Models.UserViewModel

@{
    ViewData["Title"] = "Account Details";
}

<h1>Account Details</h1>

<div>
	<hr />
	<dl class="row">
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.UserID)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.UserID)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.FirstName_)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.FirstName_)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.LastName_)
		</dt>
		<dt class="col-sm-10">
			@Html.DisplayFor(model => model.LastName_)
		</dt>
		<dd class="col-sm-2">
			@Html.DisplayNameFor(model => model.Email)
		</dd>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Email)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Password)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Password)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Role)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Role)
		</dd>

		@{ if (Context.Request.Cookies["role"] == "customer") {
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.Address)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.Address)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.City)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.City)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.State)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.State)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.Zipcode)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.Zipcode)
			</dd>
			}
			else {
				<dt class="col-sm-2">
					@Html.DisplayNameFor(model => model.Date)
				</dt>
				<dd class="col-sm-10">
					@Html.DisplayFor(model => model.Date)
				</dd>
			}
		}
		</dl>
</div>
<div>
	<a asp-action="Edit" asp-route-id="@Model.UserID">Edit Account</a>
	<br />
	@if (Context.Request.Cookies["role"] == "customer") {
		<a asp-controller="Customer" asp-action="Data" asp-route-id="@Model.UserID">Generate Transaction History</a>
	}
</div>
@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

databases-pos-vs/databases-pos-vs/Views/User/Edit.cshtml
@model databseApp.Models.UserViewModel

@{
    ViewData["Title"] = "Edit Account Information";
}

<h1>@ViewData["Title"]</h1>

<div class="row">
	<div class="col-md-4">
		<form asp-action="Edit">
			<input type="hidden" asp-for="UserID" />

			<div class="form-group">
				<label asp-for="Email" class="control-label"></label>
				<input type="email" asp-for="Email" class="form-control" required />
				<span asp-validation-for="Email" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Password" class="control-label"></label>
				<input asp-for="Password" class="form-control" required />
				<span asp-validation-for="Password" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="FirstName_" class="control-label"></label>
				<input asp-for="FirstName_" class="form-control" required />
				<span asp-validation-for="FirstName_" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="LastName_" class="control-label"></label>
				<input asp-for="LastName_" class="form-control" required />
				<span asp-validation-for="LastName_" class="text-danger"></span>
			</div>
			@{ if (Context.Request.Cookies["role"] == "customer") {
				<div class="form-group">
					<label asp-for="Address" class="control-label"></label>
					<input asp-for="Address" class="form-control" />
					<span asp-validation-for="Address" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="City" class="control-label"></label>
					<input asp-for="City" class="form-control" />
					<span asp-validation-for="City" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="State" class="control-label"></label>
					<input asp-for="State" class="form-control" />
					<span asp-validation-for="State" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="Zipcode" class="control-label"></label>
					<input asp-for="Zipcode" class="form-control" />
					<span asp-validation-for="Zipcode" class="text-danger"></span>
				</div>
				}
			}
			<div class="form-group">
				<input type="submit" value="Next">
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Details">Back to Account Details</a>
</div>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

databases-pos-vs/databases-pos-vs/Views/User/EmployeeDetails.cshtml
@model databseApp.Models.UserViewModel
@{
    ViewData["Title"] = "Your Details";
}

<div class="jumbotron">
	<h1>@ViewData["Title"]</h1>
</div>


<table class="table table-bordered">


</table>


<h1> testing employee</h1>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

databases-pos-vs/databases-pos-vs/Views/User/UserIndex.cshtml
@model databseApp.Models.UserViewModel
@{
    ViewData["Title"] = "Login";
}


<div class="text-center">
	<h1>@ViewData["Title"]</h1>
	<form asp-action="UserIndex">

		<label asp-for="Email">Email</label>
		<input asp-for="Email" type="email" name="Email" placeholder="yourname@email.com" required>

		<label asp-for="Password">Password</label>
		<input asp-for="Password" type="password" name="Password" placeholder="password" required>

		<p><input type="submit" value="Login"></p>

		<div class="create-account">
			<a asp-area="" asp-controller="User" asp-action="Create">Create account</a>
		</div>

	</form>
</div>


@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}